FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir flask requests

CMD ["python", "-c", "print('Hola desde un contenedor optimizado')"]
