FROM alpine:3.20

# Crear usuario y grupo sin privilegios
RUN addgroup -S app && adduser -S -G app app

# Cambiar al usuario no root
USER app

# Comando: mostrar UID, GID y nombre de usuario
CMD ["sh", "-c", "echo Usuario: $(id -un), UID: $(id -u), GID: $(id -g)"]
